tests.py: Fix UTF-8 Python3 problem on Windows
This fix fixes two errors in the test suite:

---
1.
ERROR: test_quotes (__main__.ZENLangTestCase)
...
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 985: character maps to <undefined>

2.
ERROR: test_getting_links (__main__.ZLTLangTestCase)
...
StopIteration
---

This can be fixed with
parses = open(testfile, encoding="utf-8")
but it is not Python2-compatible. So the approach taken here is to read
the parses file in binary mode.

With this fix, all the tests pass also under Python3.