configure minisat: Fix C++ function check problem on Gentoo
(Solving issue #442.)

"AC_CHECK_DECL([mkLit], ..." uses the C++ code line "(void) mkLit;"
which causes the errro:
conftest.cpp:44:10: error: conversion to void cannot resolve address of overloaded function
   (void) mkLit;
(gcc version 4.9.3 (Gentoo 4.9.3 p1.5, pie-0.6.4))

Solve this by specifying its arguments.
(This function has only one definition. On higher gcc versions I didn't
encounter this problem.)