make maintainer-clean: Add removing pp_lexer.c from the source tree
Background:
The automatic maintainer-clean target tries to remove pp_lexer.c from
the build directory. However, it is created in the source directory.
This causes a problem after compiling in Windows even after
"make maintainer-clean":
pp_lexer.c:569:16: fatal error: io.h: No such file or directory