MinGW: Changes for Java bindings
1. Move -D_JNI_IMPLEMENTATION_ from the linkage flags to the compilation
flags of the bindings. It is not needed for non-Windows system, but is
not harmful.

2. Leave -Wl,--kill-at only in the linkage flags of the bindings.

3. Arrange for Windows pathname in build.html, since javac on Windows
doesn't understand MSYS filesystem pathnames .

4. Solve the following:
 win32/jni_md.h:34:9: error: ‘__int64’ does not name a type

5. The standard pathname of JAVA_HOME on Windows contains a blank,
and automake cannot handle that (no way to quote it). Convert it to
short DOS path (which cannot contains blanks).