Fix TypeError (#78)
Fix the following error, that causes 3 tests to fail:
  File ".../bindings/python/linkgrammar.py", line 313, in diagram
    return clg.linkage_print_diagram(self._obj, display_walls, screen_width)
TypeError: in method 'linkage_print_diagram', argument 2 of type 'bool'